const DEFAULT={youtube:'https://www.youtube.com/channel/UC5yhMjSb7zw-tE2Nm2wV_NA',tiktok:'https://www.tiktok.com/@lakabraoficial',discord:'#',whatsapp:'https://wa.me/',paypal:'https://www.paypal.com/donate/?business=jonnyguzman358%40gmail.com&currency_code=USD',stats:{videos:0,community:0,hours:126,clips:0},manualVideos:[],manualClips:[],accounts:[{title:'Cuenta Prime Rush #1',price:'Consultar',rank:'Leyenda',level:'Nivel 75',status:'Disponible',desc:'Cuenta disponible. Revisa las fotos y el video antes de contactar.',video:'',contact:'https://wa.me/',photos:['/assets/hero-banner.jpg','/assets/og-image.jpg'],active:true},{title:'Cuenta Prime Rush #2',price:'Consultar',rank:'Leyenda',level:'Nivel 75',status:'Disponible',desc:'Cuenta disponible para mostrar otra opción en la tienda.',video:'',contact:'https://wa.me/',photos:['/assets/og-image.jpg','/assets/hero-banner.jpg'],active:true},{title:'Cuenta Prime Rush #3',price:'Consultar',rank:'Leyenda',level:'Nivel 75',status:'Disponible',desc:'Cuenta disponible. Agrega fotos reales desde el panel privado.',video:'',contact:'https://wa.me/',photos:['/assets/hero-banner.jpg','/assets/profile-lakabra.jpg'],active:true}]};
let settings={...DEFAULT};
async function loadSettings(){
  try{
    const {data,error}=await window.lakabraDb.from('site_settings').select('data').eq('id','main').single();
    if(error) throw error;
    return {...DEFAULT,...(data?.data||{})};
  }catch(error){
    console.error('No se pudo cargar Supabase:',error);
    return {...DEFAULT};
  }
}
async function init(){settings=await loadSettings();startApp()}
function startApp(){

const loader=document.getElementById('loader');window.addEventListener('load',()=>setTimeout(()=>loader?.classList.add('hide'),650));document.getElementById('year').textContent=new Date().getFullYear();
const glow=document.getElementById('cursorGlow');window.addEventListener('mousemove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));
const c=document.getElementById('particles'),ctx=c.getContext('2d');let w,h,parts=[];function resize(){w=c.width=innerWidth;h=c.height=innerHeight;parts=Array.from({length:Math.min(95,Math.floor(w*h/18000))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35,r:Math.random()*2+1}))}resize();addEventListener('resize',resize);function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(93,220,255,.7)';parts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.strokeStyle='rgba(93,220,255,.08)';for(let i=0;i<parts.length;i++)for(let j=i+1;j<parts.length;j++){let a=parts[i],b=parts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<130){ctx.globalAlpha=1-d/130;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.globalAlpha=1}}requestAnimationFrame(draw)}draw();
const i18n={es:{hero:'Prime Rush, clips y comunidad. Entra, mira el contenido, revisa cuentas disponibles y conecta conmigo.'},pt:{hero:'Prime Rush, clipes e comunidade. Entre, veja o conteúdo, confira contas disponíveis e conecte comigo.'},en:{hero:'Prime Rush, clips and community. Watch content, check available accounts and connect with me.'}};
const langBtn=document.getElementById('langBtn'),langMenu=document.getElementById('langMenu');langBtn.onclick=()=>langMenu.classList.toggle('show');langMenu.querySelectorAll('button').forEach(b=>b.onclick=()=>{const l=b.dataset.lang;localStorage.setItem('lakabraLang',l);langBtn.textContent=l.toUpperCase()+' ▾';heroText.textContent=i18n[l]?.hero||i18n.es.hero;langMenu.classList.remove('show')});const currentLang=localStorage.getItem('lakabraLang')||'es';langBtn.textContent=currentLang.toUpperCase()+' ▾';heroText.textContent=i18n[currentLang]?.hero||i18n.es.hero;
youtubeBtn.href=settings.youtube;tiktokBtn.href=settings.tiktok;donateBtn.href=settings.paypal;whatsappLink.href=settings.whatsapp;floatingWhatsapp.href=settings.whatsapp;discordLink.href=settings.discord||'#';
function youtubeId(url){if(!url)return'';let m=url.match(/[?&]v=([^&]+)/)||url.match(/youtu\.be\/([^?&]+)/)||url.match(/shorts\/([^?&/]+)/)||url.match(/embed\/([^?&/]+)/);return m?m[1]:''}function ytThumb(id){return id?`https://i.ytimg.com/vi/${id}/hqdefault.jpg`:'/assets/hero-banner.jpg'}function embedUrl(item){const id=item.videoId||youtubeId(item.url);return item.platform==='youtube'&&id?`https://www.youtube.com/embed/${id}?autoplay=1&mute=1&controls=0&rel=0&playsinline=1`:''}function normalize(v,kind='youtube'){const id=youtubeId(v.url);return{title:v.title||'Video destacado',desc:v.desc||'',platform:(v.platform||kind).toLowerCase(),type:(v.type||kind).toLowerCase(),url:v.url||'',thumb:v.thumb||(id?ytThumb(id):'/assets/hero-banner.jpg'),videoId:id,published:v.published||''}}
const videos=(settings.manualVideos||[]).map(x=>normalize(x,'youtube'));const clips=(settings.manualClips||[]).map(x=>normalize(x,'shorts'));if(!videos.length)videos.push({title:'Agrega videos desde Admin',desc:'Pega enlaces exactos de YouTube o TikTok.',platform:'youtube',type:'youtube',url:settings.youtube,thumb:'/assets/hero-banner.jpg'});if(!clips.length)clips.push({title:'Headshot clutch',desc:'Clip destacado demo.',platform:'youtube',type:'shorts',url:settings.youtube,thumb:'/assets/hero-banner.jpg'},{title:'1v4 imposible',desc:'Clip TikTok demo.',platform:'tiktok',type:'tiktok',url:settings.tiktok,thumb:'/assets/profile-lakabra.jpg'});
function formatCount(n){n=Number(n)||0;if(n>=1000000)return(n/1000000).toFixed(n%1000000?1:0)+'M';if(n>=1000)return(n/1000).toFixed(n%1000?1:0)+'K';return String(n)}statVideos.textContent=formatCount(settings.stats.videos||videos.length);statCommunity.textContent=formatCount(settings.stats.community||0);statHours.textContent=formatCount(settings.stats.hours||126);statClips.textContent=formatCount(settings.stats.clips||clips.length);
let allItems=[...videos,...clips],currentFilter='all';function setFeatured(item){featuredPlatform.textContent=item.platform;featuredTitle.textContent=item.title;featuredDesc.textContent=item.desc||'Contenido oficial de LAKABRA';openFeatured.href=item.url||settings.youtube;mainPreview.classList.remove('previewing');mainPreview.querySelector('img').src=item.thumb||'/assets/hero-banner.jpg';mainPreview.querySelector('iframe').src='';mainPreview.dataset.embed=embedUrl(item)}
function mediaCard(item){const d=document.createElement('article');d.className='media-item';d.innerHTML=`<div class="media-thumb"><img src="${item.thumb}" alt="${item.title}"><span class="card-play">▶</span><iframe title="preview"></iframe></div><div><span class="platform-pill">${item.platform}</span><h3>${item.title}</h3><p>${item.desc||''}</p><div class="media-meta">${item.published||''}</div></div>`;d.onclick=()=>item.url&&window.open(item.url,'_blank');let timer;d.onmouseenter=()=>{setFeatured(item);const emb=embedUrl(item);if(emb)timer=setTimeout(()=>{d.classList.add('previewing');d.querySelector('iframe').src=emb},650)};d.onmouseleave=()=>{clearTimeout(timer);d.classList.remove('previewing');d.querySelector('iframe').src=''};return d}
function clipCard(item){const d=document.createElement('article');d.className='clip-tile';d.innerHTML=`<img src="${item.thumb}" alt="${item.title}"><span class="platform-pill">${item.platform}</span><span class="clip-title">${item.title}</span><span class="card-play">▶</span><iframe title="preview"></iframe>`;d.onclick=()=>item.url&&window.open(item.url,'_blank');let timer;d.onmouseenter=()=>{const emb=embedUrl(item);if(emb)timer=setTimeout(()=>{d.classList.add('previewing');d.querySelector('iframe').src=emb},650)};d.onmouseleave=()=>{clearTimeout(timer);d.classList.remove('previewing');d.querySelector('iframe').src=''};return d}
function renderItems(){const filtered=allItems.filter(x=>currentFilter==='all'||x.platform===currentFilter||x.type===currentFilter);playlist.innerHTML='';filtered.forEach(x=>playlist.appendChild(mediaCard(x)));if(filtered[0])setFeatured(filtered[0])}document.querySelectorAll('#contentFilters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#contentFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;renderItems()});renderItems();clipRow.innerHTML='';clips.forEach(x=>clipRow.appendChild(clipCard(x)));syncStatus.textContent='Los videos se controlan desde Admin. Sin API ni lucha.';
let mainTimer;mainPreview.onmouseenter=()=>{const emb=mainPreview.dataset.embed;if(emb)mainTimer=setTimeout(()=>{mainPreview.classList.add('previewing');mainPreview.querySelector('iframe').src=emb},600)};mainPreview.onmouseleave=()=>{clearTimeout(mainTimer);mainPreview.classList.remove('previewing');mainPreview.querySelector('iframe').src=''};
function accountPhotos(a){return (a.photos||[]).filter(Boolean).length?(a.photos||[]).filter(Boolean):['/assets/hero-banner.jpg']}function renderAccounts(){const arr=(settings.accounts||DEFAULT.accounts).filter(a=>a.active!==false);accountsGrid.innerHTML='';if(!arr.length){accountsGrid.innerHTML='<div class="empty-state">No hay cuentas publicadas todavía. Agrégalas desde Admin.</div>';return}arr.forEach((a,i)=>{const photos=accountPhotos(a);const card=document.createElement('article');card.className='account-card';card.innerHTML=`<div class="account-cover"><img src="${photos[0]}" alt="${a.title||'Cuenta Prime Rush'}"><span class="account-badge">${a.status||'Disponible'}</span><span class="account-photos">${photos.length} fotos</span></div><div class="account-body"><h3>${a.title||'Cuenta Prime Rush'}</h3><div class="account-meta"><span>${a.rank||'Rango'}</span><span>${a.level||'Nivel'}</span></div><p>${a.desc||''}</p><div class="account-price">${a.price||'Consultar'}</div><button class="btn btn-green" type="button">Ver detalles</button></div>`;card.onclick=()=>openAccount(a);accountsGrid.appendChild(card)})}renderAccounts();
function videoEmbed(url){const id=youtubeId(url);if(id)return`<div class="modal-video"><iframe src="https://www.youtube.com/embed/${id}" allowfullscreen></iframe></div>`;return url?`<div class="modal-video"><a href="${url}" target="_blank">Ver video de la cuenta</a></div>`:''}function openAccount(a){const photos=accountPhotos(a);modalMainImage.src=photos[0];modalThumbs.innerHTML='';photos.forEach((p,idx)=>{const im=document.createElement('img');im.src=p;im.className=idx===0?'active':'';im.onclick=()=>{modalMainImage.src=p;modalThumbs.querySelectorAll('img').forEach(x=>x.classList.remove('active'));im.classList.add('active')};modalThumbs.appendChild(im)});modalStatus.textContent=a.status||'Disponible';modalTitle.textContent=a.title||'Cuenta Prime Rush';modalPrice.textContent=a.price||'Consultar';modalDesc.textContent=a.desc||'';modalVideoBox.innerHTML=videoEmbed(a.video||'');modalContact.href=a.contact||settings.whatsapp;accountModal.classList.add('show');accountModal.setAttribute('aria-hidden','false')}modalClose.onclick=()=>accountModal.classList.remove('show');accountModal.onclick=e=>{if(e.target===accountModal)accountModal.classList.remove('show')};
subscribeForm.onsubmit=async e=>{e.preventDefault();const email=subscriberInput.value.trim();if(!email)return;const {error}=await window.lakabraDb.from('subscribers').insert({email});if(error&&error.code!=='23505'){console.error(error);alert('No se pudo registrar el correo. Inténtalo nuevamente.');return}subscriberInput.value='';await updateSubCount();alert('Te agregaste a la lista LAKABRA')};async function updateSubCount(){const {count,error}=await window.lakabraDb.from('subscribers').select('*',{count:'exact',head:true});subscriberCount.textContent=(error?0:(count||0))+' seguidores registrados'}updateSubCount();contactForm.onsubmit=async e=>{e.preventDefault();const payload={name:contactName.value.trim(),contact:contactContact.value.trim(),message:contactMessage.value.trim()};const {error}=await window.lakabraDb.from('messages').insert(payload);if(error){console.error(error);alert('No se pudo enviar el mensaje. Inténtalo nuevamente.');return}contactForm.reset();alert('Mensaje enviado correctamente')};
const mob=document.createElement('div');mob.className='mobile-bottom-nav';mob.innerHTML='<a href="#inicio">Inicio</a><a href="#videos">TV</a><a href="#cuentas">Cuentas</a><a href="#contacto">Contacto</a>';document.body.appendChild(mob);

// Eliminar cualquier acceso visible al panel desde la web pública
document.querySelectorAll('.admin-float, a[href="admin.html"], a[href="/admin.html"]').forEach(el=>el.remove());

}
init();
