-- Ejecuta todo este archivo en Supabase > SQL Editor > New query > Run

create table if not exists public.site_settings (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

insert into public.site_settings (id, data)
values ('main', jsonb_build_object(
  'youtube','https://www.youtube.com/channel/UC5yhMjSb7zw-tE2Nm2wV_NA',
  'tiktok','https://www.tiktok.com/@lakabraoficial',
  'discord','#',
  'whatsapp','https://wa.me/',
  'paypal','https://www.paypal.com/donate/?business=jonnyguzman358%40gmail.com&currency_code=USD',
  'stats',jsonb_build_object('videos',0,'community',0,'hours',126,'clips',0),
  'manualVideos','[]'::jsonb,
  'manualClips','[]'::jsonb,
  'accounts','[]'::jsonb
))
on conflict (id) do nothing;

alter table public.site_settings enable row level security;
alter table public.messages enable row level security;
alter table public.subscribers enable row level security;

drop policy if exists "Public can read site settings" on public.site_settings;
create policy "Public can read site settings"
on public.site_settings for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can insert site settings" on public.site_settings;
create policy "Authenticated can insert site settings"
on public.site_settings for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can update site settings" on public.site_settings;
create policy "Authenticated can update site settings"
on public.site_settings for update
to authenticated
using (true)
with check (true);

drop policy if exists "Public can send messages" on public.messages;
create policy "Public can send messages"
on public.messages for insert
to anon, authenticated
with check (char_length(name) between 1 and 120 and char_length(contact) between 1 and 200 and char_length(message) between 1 and 3000);

drop policy if exists "Authenticated can read messages" on public.messages;
create policy "Authenticated can read messages"
on public.messages for select
to authenticated
using (true);

drop policy if exists "Public can subscribe" on public.subscribers;
create policy "Public can subscribe"
on public.subscribers for insert
to anon, authenticated
with check (position('@' in email) > 1 and char_length(email) <= 320);

drop policy if exists "Authenticated can read subscribers" on public.subscribers;
create policy "Authenticated can read subscribers"
on public.subscribers for select
to authenticated
using (true);
